spring:
  application:
    name: order-service
  config:
    import: "optional:configserver:http://localhost:8888"
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      group-id: ${spring.application.name}
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      auto-offset-reset: earliest
    properties:
      spring.json.trusted.packages: "com.microservices.pro.*"
      spring.json.type.mapping: "orderPlaced:com.microservices.pro.order.events.OrderPlacedEvent,inventoryReserved:com.microservices.pro.order.events.InventoryReservedEvent,inventoryReservationFailed:com.microservices.pro.order.events.InventoryReservationFailedEvent,paymentCompleted:com.microservices.pro.order.events.PaymentCompletedEvent,paymentFailed:com.microservices.pro.order.events.PaymentFailedEvent,inventoryReleased:com.microservices.pro.order.events.InventoryReleasedEvent,orderConfirmed:com.microservices.pro.order.events.OrderConfirmedEvent,orderCancelled:com.microservices.pro.order.events.OrderCancelledEvent"

server:
  port: 8082

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: health,info